/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Liste aller Pflegeplan-Maßnahmen, die auf einem Kartenausschnitt einer Stromtrasse abgebildet sind. Maßnahmen sind in farblichen Rechtecken beschrieben.
 */
export type MassnahmenSchema = {
  /**
   * ID der Maßnahme, oben im Rechteck zu finden (z.B. '0.1' oder '10.2'). Dient als eindeutiger Identifikator innerhalb des Blattes.
   */
  peId: string;
  /**
   * Art der Maßnahme (z.B. 'Einzelentnahme', 'Standortpflege Mast').
   */
  type:
    | "Einzelentnahme"
    | "Einzelentnahme 20 cm bis 40 cm"
    | "Einzelentnahme 41 cm bis 60 cm"
    | "Kroneneinkürzung"
    | "Kronenrückschnitt"
    | "Entbuschen"
    | "Durchforsten"
    | "Auf den Stock setzen"
    | "Heckenschnitt"
    | "Mulchen"
    | "Geh- und Fahrweg (Mulchstreifen)"
    | "Standortpflege Mast"
    | "Standortpflege unter Traversen";
  /**
   * Art der Aufarbeitung des entnommenen Materials (z.B. 'Standard', 'Astwerk häckseln').
   */
  aufarbeitung:
    | "Standard"
    | "Astwerk Häckseln"
    | "Astwerk Häckseln & Stammholz Meter"
    | "Astwerk Häckseln & Stammholz nach Vorgabe zuschneiden"
    | "Astwerk Häckseln & Stammholz nach Vorgabe rücken und zuschneiden"
    | "Astwerk Standard"
    | "Astwerk Standard & Stammholz Meter"
    | "Astwerk Standard & Stammholz nach Vorgabe zuschneiden"
    | "Astwerk Standard & Stammholz nach Vorgabe rücken und zuschneiden"
    | "Astwerk Abfahren"
    | "Astwerk & Stammholz Abfahren";
  /**
   * Die auf dem Plan angegebene Gesamtfläche in Quadratmetern, bei flächenbezogenen Maßnahmen (z.B. '4186m²' für Durchforsten).
   */
  fläche_m2_gesamt?: number;
  /**
   * Die berechnete oder bearbeitete Fläche in Quadratmetern, oft hinter einer Prozentangabe (z.B. '33% - 1381m²' -> 1381m²). Nur bei flächenbezogenen Maßnahmen.
   */
  fläche_m2?: number;
  /**
   * Der prozentuale Anteil der Bearbeitung ('100%' | '50%'), steht vor der Flächenangabe, bei flächenbezogenen Maßnahmen.
   */
  prozent?: number;
  /**
   * Die angegebene Stückzahl ('5 Einzelentnahme...'), bei Einzel- oder Kronen-Maßnahmen.
   */
  anzahl_stk?: number;
  /**
   * Wichtige Informationen zur Durchführung der Maßnahme als Freitext (z.B. spezifische Baumarten wie 'Ahorn, Haselnuss, Kirsche', oder besondere Anweisungen).
   */
  details: string;
  /**
   * Bauleit-Nummer der Stromleitung BL als 4-stelliger String (z.B. 'BL 4511' -> '4511'), meistens bei Standortpflege-Maßnahmen.
   */
  bl_nr?: string;
  /**
   * Mastnummer als 4-stelliger String, mit voranstehenden Nullen aufgefüllt, + optionale Buchstaben (z.B. 'Mast 23' -> '0023', 'Mast 35A' -> '035A'), meistens bei Standortpflege-Maßnahmen.
   */
  mast_nr?: string;
  /**
   * Informationen zur Kontaktperson (Name, Telefon, E-Mail, etc.), falls relevant für die Maßnahme.
   */
  kontakt?: string;
  /**
   * Geschätzter Vertrauenswert (0-100) für die Genauigkeit der extrahierten Daten dieser Maßnahme.
   */
  confidence: number;
  /**
   * Die Koordinaten des Rechtecks im Bild (in Pixeln), in dem die Maßnahme (das Beschreibungsfeld) gefunden wurde.
   */
  rectangle: {
    /**
     * X-Koordinate der oberen linken Ecke
     */
    x: number;
    /**
     * Y-Koordinate der oberen linken Ecke
     */
    y: number;
    /**
     * Breite des Rechtecks
     */
    width: number;
    /**
     * Höhe des Rechtecks
     */
    height: number;
    [k: string]: unknown;
  };
  /**
   * GeoJSON-Punkt-Geometrie des Mittelpunkts oder eines Referenzpunkts der Maßnahme auf der Karte. Dieser Punkt muss manuell oder durch Georeferenzierung hinzugefügt werden.
   */
  geometry?: {
    type: "Point";
    /**
     * Koordinaten der Geometrie [Longitude, Latitude]
     *
     * @minItems 2
     * @maxItems 3
     */
    coordinates: [number, number] | [number, number, number];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
