/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Liste der Masten, die auf dem Kartenausschnitt des Plans sichtbar sind.
 */
export type MastenSchema = {
  /**
   * Die Mastnummer, die auf der Karte abgebildet ist. Sollte auf 4 Stellen mit voranstehenden Nullen aufgefüllt werden, mit optionalen Buchstaben (z.B. '38' -> '0038', '38A' -> '038A').
   */
  mastId: string;
  /**
   * Die Bauleit-Nummer als 4-stelliger String (z.B. 'BL 4511' -> '4511'), zu der der Mast gehört, falls diese explizit am Mast vermerkt ist (z.B. '36(2388)' -> '2388').
   */
  bl_nr?: string;
  /**
   * Die Koordinaten des Rechtecks im Bild (in Pixeln), das das Mastsymbol (Kästchen mit Kreuz) umschließt.
   */
  symbol_rectangle: {
    /**
     * X-Koordinate der oberen linken Ecke
     */
    x: number;
    /**
     * Y-Koordinate der oberen linken Ecke
     */
    y: number;
    /**
     * Breite des Rechtecks
     */
    width: number;
    /**
     * Höhe des Rechtecks
     */
    height: number;
    [k: string]: unknown;
  };
  /**
   * Die Koordinaten des Rechtecks im Bild (in Pixeln), das die Mastnummer (Text) umschließt.
   */
  text_rectangle: {
    /**
     * X-Koordinate der oberen linken Ecke
     */
    x: number;
    /**
     * Y-Koordinate der oberen linken Ecke
     */
    y: number;
    /**
     * Breite des Rechtecks
     */
    width: number;
    /**
     * Höhe des Rechtecks
     */
    height: number;
    [k: string]: unknown;
  };
  /**
   * Geschätzter Vertrauenswert (0-100) für die Erkennung dieses Mastes und seiner Daten auf der Karte.
   */
  confidence: number;
  /**
   * GeoJSON-Punkt-Geometrie des Maststandorts. Dieser Punkt muss manuell oder durch Georeferenzierung hinzugefügt werden, da er nicht direkt aus dem Bild extrahiert werden kann.
   */
  geometry?: {
    type: "Point";
    /**
     * Koordinaten der Geometrie [Longitude, Latitude]
     *
     * @minItems 2
     * @maxItems 3
     */
    coordinates: [number, number] | [number, number, number];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}[];
