/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Informationen zu einem Vegetationspflegeplan (BMP-/ÖTM-Plan) für Hochspannungsleitungen
 */
export interface PlaninfoSchema {
  /**
   * Eindeutige PDF-Plan-ID (z.B. '4113_Limburg-Weilburg_0003_9_16_111024'). Eine generierte ID, die wichtige Metadaten des Plans zusammenfasst.
   */
  planId?: string;
  /**
   * Typ des Plans, je nachdem von welchem Betreiber der Plan stammt. 'BMP' (Biotopmanagementplan) oder 'ÖTM' (Ökologischer Trassenmanagementplan). Im Dateinamen ist oft ein 'OETM' oder 'ÖTM' enthalten.
   */
  planType?: "BMP" | "ÖTM";
  /**
   * Name des Betreibers der Hochspannungsleitung.
   */
  betreiber: "Westnetz" | "Rhein Energie" | "Rheinische Netzgesellschaft" | "RWE" | "RWE Power" | "Amprion";
  /**
   * Detaillierte Beschreibung der Hochspannungsleitung, oft inklusive Spannungsebenen (z.B. '110-/220-/380-kV-Höchstspannungsfreileitung ...').
   */
  beschreibung: string;
  /**
   * Bauleit-Nummer der Stromleitung (z.B. 'BL 2449'). Es wird empfohlen, nur die Zahl als String zu speichern, z.B. '2449'.
   */
  bl: string;
  /**
   * Definierter Start- und End-Mast des im Plan behandelten Abschnitts, wie auf dem Deckblatt angegeben. Zusätzliche Angaben wie 'Po' (Portal im Umspannwerk) oder Verweise auf andere BL-Nummern werden ignoriert.
   */
  mastbereich: {
    /**
     * Start Mast als String. Sollte auf 4 Stellen mit voranstehenden Nullen aufgefüllt werden, mit optionalen Buchstaben (z.B. '28' -> '0028', '28A' -> '028A').
     */
    start: string;
    /**
     * End Mast als String. Sollte auf 4 Stellen mit voranstehenden Nullen aufgefüllt werden, mit optionalen Buchstaben (z.B. '31' -> '0031', '35A' -> '035A').
     */
    end: string;
    [k: string]: unknown;
  };
  /**
   * Name der Hochspannungsleitung (z.B. 'St. Tönis - Osterath'). Manchmal identisch mit der Beschreibung.
   */
  ltg_name?: string;
  /**
   * Name des spezifischen Abschnitts der Leitung (z.B. 'Pkt. Schreckenend - Osterath').
   */
  abschnitt?: string;
  /**
   * Region oder Kreis, in dem der Plan gültig ist (z.B. 'Rhein-Lahn-Kreis').
   */
  region: string;
  /**
   * Los-ID, falls vorhanden. Tritt bei ÖTM-Plänen auf (z.B. 'Los 2006 Köln' -> '2006').
   */
  losId?: "2006" | "2008" | "2009";
  /**
   * Los-Name, falls vorhanden. Tritt bei ÖTM-Plänen auf (z.B. 'Los 2006 Köln' -> 'Köln').
   */
  losName?: "Köln" | "Düsseldorf-Neuss" | "Mönchengladbach-Grevenbroich";
  /**
   * Projekt-Nummer, falls vorhanden. Tritt bei BMP-Plänen auf (z.B. 'Projekt 01080' -> '01080').
   */
  projekt?: string;
  /**
   * Blattnummer des aktuellen Plans. Sollte auf 4 Stellen mit voranstehenden Nullen aufgefüllt werden (z.B. '10' -> '0010').
   */
  blatt: string;
  /**
   * Nummer des Referenzplans (z.B. 'LP23880006'), zu finden hinter 'Referenzplan: xxxxxxxx'.
   */
  referenzplan: string;
  /**
   * Datum der letzten Ausgabe im Format DDMMYY (z.B. 'AUSGABE: 11.10.24 11:26:07' -> '111024').
   */
  ausgabe: string;
  /**
   * Maßstab des Plans (z.B. '1:2000').
   */
  maßstab?: string;
  /**
   * Liste der Gemarkungen, die auf dem Blatt aufgeführt sind (z.B. 'KÖLN'). Die Werte sollten in Großbuchstaben gespeichert werden. Es können mehrere vorhanden sein.
   */
  gemarkung?: string[];
  /**
   * Liste der Gemeinden, die auf dem Blatt aufgeführt sind (z.B. 'Wesseling'). Es können mehrere vorhanden sein.
   */
  gemeinde?: string[];
  /**
   * Liste der Verbandsgemeinden, die auf dem Blatt aufgeführt sind (z.B. 'Köln, Stadt'). Es können mehrere vorhanden sein.
   */
  verbandsgemeinde?: string[];
  /**
   * Liste der Kreise, die auf dem Blatt aufgeführt sind (z.B. 'Rhein-Sieg-Kreis'). Es können mehrere vorhanden sein.
   */
  kreis?: string[];
  /**
   * Liste der Regierungsbezirke, die auf dem Blatt aufgeführt sind (z.B. 'Köln'). Es können mehrere vorhanden sein.
   */
  reg_bezirk?: string[];
  /**
   * Liste der Länder, die auf dem Blatt aufgeführt sind (z.B. 'Nordrhein-Westfalen'). Es können mehrere vorhanden sein.
   */
  land?: string[];
  [k: string]: unknown;
}
